# Site settings
title: EasyHook
email: spazzarama@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The reinvention of Windows API Hooking
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://easyhook.github.io" # the base hostname & protocol for your site
twitter_username: spazzarama
github_username:  spazzarama

# Build settings
markdown: kramdown
collections:
  releases:
    output: false
  tutorials:
    output: true